// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjXNp9ZZAaYbXJI5BFlaidIrOcqj4G8HY',
    appId: '1:625441822214:web:2490de7a151f576ed3d587',
    messagingSenderId: '625441822214',
    projectId: 'fireebasepraticeshh',
    authDomain: 'fireebasepraticeshh.firebaseapp.com',
    storageBucket: 'fireebasepraticeshh.appspot.com',
    measurementId: 'G-TRQKXBCL6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG1IyvkR_gVNfXNJG280Bvc3MtFy1wkMw',
    appId: '1:625441822214:android:96e97fa894411c2ad3d587',
    messagingSenderId: '625441822214',
    projectId: 'fireebasepraticeshh',
    storageBucket: 'fireebasepraticeshh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYwqqwnFDlhBwjVCWmhyCJVW4bUZDFgk',
    appId: '1:625441822214:ios:9bcf61e7bb0c80c7d3d587',
    messagingSenderId: '625441822214',
    projectId: 'fireebasepraticeshh',
    storageBucket: 'fireebasepraticeshh.appspot.com',
    iosClientId: '625441822214-c127qaa1df1omtk0g8dg50fbh2du9n2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterPra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYYwqqwnFDlhBwjVCWmhyCJVW4bUZDFgk',
    appId: '1:625441822214:ios:9bcf61e7bb0c80c7d3d587',
    messagingSenderId: '625441822214',
    projectId: 'fireebasepraticeshh',
    storageBucket: 'fireebasepraticeshh.appspot.com',
    iosClientId: '625441822214-c127qaa1df1omtk0g8dg50fbh2du9n2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseFlutterPra',
  );
}
